# Generated by Django 5.2.10 on 2026-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='case_token',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_identity_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Action Taken', 'Action Taken'), ('Resolved', 'Resolved')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('counsellor', 'Counsellor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
