# Generated by Django 5.2.10 on 2026-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('counsellor', 'Counsellor'), ('admin', 'Admin'), ('security', 'Security Staff')], default='student', max_length=20),
        ),
    ]
