# Generated by Django 5.2.10 on 2026-01-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_incident_options_incident_evidence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-is_emergency', '-updated_at']},
        ),
        migrations.AddField(
            model_name='incident',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to='sos_recordings/'),
        ),
    ]
