# Generated by Django 5.2.10 on 2026-01-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_incident_options_incident_is_emergency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('counsellor', 'Counsellor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
